version: "3.9"
services:
  order-service:
    restart: always
    container_name: order-service
    build: order-service
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${ORDER_SERVICE_DBNAME}
    depends_on:
      - db
    networks:
      - app-network

  product-service:
    restart: always
    container_name: product-service
    build: product-service
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${PRODUCT_SERVICE_DBNAME}
    depends_on:
      - db
    networks:
      - app-network

  messaging:
    container_name: messaging
    build: messaging
    restart: always
    environment:
      ACTIVEMQ_WEB_USER: admin
      ACTIVEMQ_WEB_PASSWORD: admin
      ACTIVEMQ_CONNECTION_USER: admin
      ACTIVEMQ_CONNECTION_PASSWORD: admin
      ACTIVEMQ_JMX_USER: admin
      ACTIVEMQ_JMX_PASSWORD: admin
    ports:
      - "8161:8161"
      - "1099:1099"
      - "61616:61616"
      - "5672:5672"
      - "61613:61613"
    networks:
      - app-network

  nginx:
    restart: always
    container_name: nginx
    build: nginx
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    build: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: application
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8004:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - app-network


networks:
  app-network:
    external: false
    name: app-network

