version: "3.9"
services:
  order-service:
    restart: always
    container_name: order-service
    build: order-service
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    build: db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: application
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8004:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - app-network


networks:
  app-network:
    external: false
    name: app-network

