CREATE TABLE IF NOT EXISTS ORDERS (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  price DOUBLE NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT UNSIGNED NOT NULL
);
