CREATE TABLE IF NOT EXISTS ORDERS (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  price DOUBLE NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  date_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id BIGINT UNSIGNED NOT NULL
);


INSERT INTO ORDERS (price, user_id) VALUES (100.0, 1);
INSERT INTO ORDERS (price, user_id) VALUES (110.0, 2);
INSERT INTO ORDERS (price, user_id) VALUES (120.0, 3);
INSERT INTO ORDERS (price, user_id) VALUES (130.0, 4);
INSERT INTO ORDERS (price, user_id) VALUES (140.0, 5);
